// GENERATED by scripts/import-work-images.mjs - do not edit by hand.
export type WorkImage = { src: string; w: number; h: number };

export const workImages: Record<string, { cover: WorkImage; images: WorkImage[] }> = {
  "a47": {
    cover: { src: "/work/a47/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/a47/01.webp", w: 1288, h: 1288 }],
  },
  "aztec-chocolate": {
    cover: { src: "/work/aztec-chocolate/cover.webp", w: 602, h: 602 },
    images: [{ src: "/work/aztec-chocolate/01.webp", w: 602, h: 602 }, { src: "/work/aztec-chocolate/02.webp", w: 602, h: 602 }, { src: "/work/aztec-chocolate/03.webp", w: 271, h: 271 }, { src: "/work/aztec-chocolate/04.webp", w: 291, h: 291 }],
  },
  "cablemaster": {
    cover: { src: "/work/cablemaster/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/cablemaster/01.webp", w: 1221, h: 1221 }],
  },
  "chatterbox-cafe": {
    cover: { src: "/work/chatterbox-cafe/cover.webp", w: 800, h: 800 },
    images: [{ src: "/work/chatterbox-cafe/01.webp", w: 800, h: 800 }, { src: "/work/chatterbox-cafe/02.webp", w: 800, h: 800 }, { src: "/work/chatterbox-cafe/03.webp", w: 800, h: 800 }, { src: "/work/chatterbox-cafe/04.webp", w: 800, h: 800 }],
  },
  "costa": {
    cover: { src: "/work/costa/cover.webp", w: 603, h: 603 },
    images: [{ src: "/work/costa/01.webp", w: 603, h: 603 }, { src: "/work/costa/02.webp", w: 603, h: 603 }, { src: "/work/costa/03.webp", w: 604, h: 604 }, { src: "/work/costa/04.webp", w: 606, h: 606 }],
  },
  "crq-technology": {
    cover: { src: "/work/crq-technology/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/crq-technology/01.webp", w: 1600, h: 1600 }],
  },
  "dealicious-mealz": {
    cover: { src: "/work/dealicious-mealz/cover.webp", w: 900, h: 1125 },
    images: [{ src: "/work/dealicious-mealz/01.webp", w: 1080, h: 1350 }, { src: "/work/dealicious-mealz/02.webp", w: 485, h: 606 }, { src: "/work/dealicious-mealz/03.webp", w: 485, h: 606 }],
  },
  "divine-dates": {
    cover: { src: "/work/divine-dates/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/divine-dates/01.webp", w: 1304, h: 1304 }],
  },
  "fad": {
    cover: { src: "/work/fad/cover.webp", w: 602, h: 602 },
    images: [{ src: "/work/fad/01.webp", w: 602, h: 602 }, { src: "/work/fad/02.webp", w: 800, h: 800 }, { src: "/work/fad/03.webp", w: 800, h: 800 }, { src: "/work/fad/04.webp", w: 800, h: 800 }],
  },
  "gulabo": {
    cover: { src: "/work/gulabo/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/gulabo/01.webp", w: 1257, h: 1257 }],
  },
  "himalaya": {
    cover: { src: "/work/himalaya/cover.webp", w: 605, h: 605 },
    images: [{ src: "/work/himalaya/01.webp", w: 605, h: 605 }, { src: "/work/himalaya/02.webp", w: 607, h: 607 }, { src: "/work/himalaya/03.webp", w: 605, h: 605 }, { src: "/work/himalaya/04.webp", w: 800, h: 800 }],
  },
  "ihop": {
    cover: { src: "/work/ihop/cover.webp", w: 604, h: 604 },
    images: [{ src: "/work/ihop/01.webp", w: 604, h: 604 }, { src: "/work/ihop/02.webp", w: 602, h: 602 }, { src: "/work/ihop/03.webp", w: 604, h: 604 }, { src: "/work/ihop/04.webp", w: 604, h: 604 }],
  },
  "innovative-pvt-ltd": {
    cover: { src: "/work/innovative-pvt-ltd/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/innovative-pvt-ltd/01.webp", w: 1155, h: 1155 }],
  },
  "marcels": {
    cover: { src: "/work/marcels/cover.webp", w: 800, h: 800 },
    images: [{ src: "/work/marcels/01.webp", w: 800, h: 800 }, { src: "/work/marcels/02.webp", w: 800, h: 800 }, { src: "/work/marcels/03.webp", w: 800, h: 800 }, { src: "/work/marcels/04.webp", w: 800, h: 800 }],
  },
  "mary-browns-chicken": {
    cover: { src: "/work/mary-browns-chicken/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/mary-browns-chicken/01.webp", w: 1342, h: 1342 }],
  },
  "mcon": {
    cover: { src: "/work/mcon/cover.webp", w: 634, h: 634 },
    images: [{ src: "/work/mcon/01.webp", w: 634, h: 634 }, { src: "/work/mcon/02.webp", w: 662, h: 662 }, { src: "/work/mcon/03.webp", w: 1600, h: 1020 }],
  },
  "pidoko-kids": {
    cover: { src: "/work/pidoko-kids/cover.webp", w: 602, h: 602 },
    images: [{ src: "/work/pidoko-kids/01.webp", w: 602, h: 602 }, { src: "/work/pidoko-kids/02.webp", w: 602, h: 602 }, { src: "/work/pidoko-kids/03.webp", w: 602, h: 602 }, { src: "/work/pidoko-kids/04.webp", w: 602, h: 602 }],
  },
  "pie-in-the-sky": {
    cover: { src: "/work/pie-in-the-sky/cover.webp", w: 602, h: 602 },
    images: [{ src: "/work/pie-in-the-sky/01.webp", w: 602, h: 602 }, { src: "/work/pie-in-the-sky/02.webp", w: 602, h: 602 }, { src: "/work/pie-in-the-sky/03.webp", w: 800, h: 800 }, { src: "/work/pie-in-the-sky/04.webp", w: 602, h: 602 }],
  },
  "prestige": {
    cover: { src: "/work/prestige/cover.webp", w: 900, h: 900 },
    images: [{ src: "/work/prestige/01.webp", w: 1245, h: 1245 }],
  },
  "suncore-solar": {
    cover: { src: "/work/suncore-solar/cover.webp", w: 602, h: 602 },
    images: [{ src: "/work/suncore-solar/01.webp", w: 602, h: 602 }, { src: "/work/suncore-solar/02.webp", w: 602, h: 602 }, { src: "/work/suncore-solar/03.webp", w: 602, h: 602 }, { src: "/work/suncore-solar/04.webp", w: 602, h: 602 }],
  },
  "the-melt": {
    cover: { src: "/work/the-melt/cover.webp", w: 800, h: 800 },
    images: [{ src: "/work/the-melt/01.webp", w: 800, h: 800 }, { src: "/work/the-melt/02.webp", w: 800, h: 800 }, { src: "/work/the-melt/03.webp", w: 800, h: 800 }, { src: "/work/the-melt/04.webp", w: 800, h: 800 }],
  },
};
